[head]
name = "arithmetic"
includes = ["types.h", "stack.h"]

[[head.types]]
type_name = "STC_bin_function"
name = "add_funcs"
args = ["STC_I64", "STC_I64", "STC_TYPE", "STC_TYPE"]
return = "void"
[head.types.method]
name = "add"
stc = true
stc_code = 2
args = [ "STC_I64", "STC_I64", "STC_TYPE", "STC_TYPE"]
return = "void"
code = []
[[head.types.match]]
argA = "STC_I64"
argB = "STC_I64"
function = "add_I64_I64"

[[head.types]]
type_name = "STC_bin_function"
name = "sub_funcs"
[head.types.method]
name = "sub"
stc = true
stc_code = 2
args = [ "STC_I64", "STC_I64", "STC_TYPE", "STC_TYPE"]
return = "void"
code = []
[[head.types.match]]
argA = "STC_I64"
argB = "STC_I64"
function = "sub_I64_I64"



[body]

[[body.method]]
name = "add_I64_I64"
args = ["STC_I64", "STC_I64", "STC_TYPE", "STC_TYPE"]
return = "void"
stc = true
stc_code = 255
stc_name = "addI"
code = ["push(arg0+arg1, STC_I64_TYPE);"]


[[body.method]]
name = "sub_I64_I64"
args = ["STC_I64", "STC_I64", "STC_TYPE", "STC_TYPE"]
return = "void"
stc = true
stc_code = 255
stc_name = "subI"
code = ["push(arg0-arg1, STC_I64_TYPE);"]